name: Build EXE

on:
  workflow_dispatch: # This allows manual triggering of the workflow


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Adjust to your project's Python version

    - name: Install dependencies
      run: |
        pip install pyinstaller
        pip install pyqt5
        pip install reportlab

    - name: Build EXE
      run: |
        pyinstaller --onefile --windowed --add-data "icons:icons" --icon=icons/icon.png HomeUnitCalculator.py  # Create the .exe

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: HomeUnitCalculator-exe
        path: dist/HomeUnitCalculator.exe  # Upload the .exe file as an artifact