name: Build HomeUnitCalculator Executable

on:
  # Manual trigger remains
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install project dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Build with Nuitka — the action handles installing Nuitka & C toolchains
      - name: Build executable with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main          # latest develop/nightly branch
          script-name: src/core/HomeUnitCalculator.py
          mode: onefile                # single-file distribution
          enable-plugins: pyqt5          # auto-collect Qt plug-ins
          include-data-dir: |
            icons=icons
          disable-console: true        # ← new
          output-dir: build
          windows-icon-from-ico: icons/icon.png   # Nuitka converts it

      # Remove the intermediate .dist folder — we only need the single EXE
      - name: Remove dist folder (keep only the EXE)
        run: Remove-Item -Recurse -Force build\HomeUnitCalculator.dist
        shell: pwsh

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: HomeUnitCalculator-${{ runner.os }}
          path: build/HomeUnitCalculator.exe