name: Build • PyInstaller

on:
  # Run manually, and also automatically on every commit to the dev or main branches.
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Keep in sync with project requirement

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # Build-only tools
          pip install pyinstaller pillow

      - name: Build one-file executable
        # PowerShell is the default shell on Windows runners; a single-line command
        # avoids line-continuation issues.
        run: |
          pyinstaller --noconsole --onefile \
                      --icon=icons/icon.png \
                      --add-data "icons;icons" \
                      src/core/HomeUnitCalculator.py

      - name: Upload artifact (single EXE)
        uses: actions/upload-artifact@v4
        with:
          name: HomeUnitCalculator-PyInstaller-${{ runner.os }}
          path: dist/HomeUnitCalculator.exe 